### ISSUE TITLE
Question: What makes it unusable on ZF2.3.9?

### ISSUE THREAD

**Issue by ingmarheinrich** [neeckeloo/NewRelic#16]
Hi,

I would like to use the lib with a ZF2.3.9 application. Is there any way?

Thanks,
  Ingmar

**Comment by neeckeloo** [comment]
Hi,

You can use the version 1.1.5 in order to use the module with ZF 2.3.9.
However, I advise you rather upgrade PHP at least to 5.5 and ZF to 2.5 if
it is not already.
PHP 5.4 no longer receive security fixes.

Nicolas

2015-09-17 13:32 GMT+02:00 Ingmar Heinrich <notifications@github.com>:

**Comment by ingmarheinrich** [comment]
We have PHP5.5, but not ZF2.5 yet.

-- 
Ingmar Heinrich <ingmar.heinrich@gmail.com>
+49.172.411.1.412

**Comment by neeckeloo** [comment]
If you want to upgrade ZF2 to 2.5, you should read this: 
http://framework.zend.com/blog/zend-framework-2-5-0-released.html
